package com.chaker.dojosandninjas.models;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;

// @Entity marks this class as a JPA entity (a table in the database)
@Entity
// @Table sets the actual table name in MySQL to "dojos"
@Table(name = "dojos")
public class Dojo {

    // @Id marks this field as the primary key
    @Id
    // The id is auto-generated by the database (AUTO_INCREMENT)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The dojo's name (e.g. "Burbank")
    private String name;

    // createdAt can never be changed after the row is inserted
    @Column(updatable = false)
    private Date createdAt;

    private Date updatedAt;

    // ONE dojo has MANY ninjas.
    // mappedBy="dojo" maps this list to the "dojo" attribute in the Ninja class
    // (the Ninja side owns the relationship / holds the foreign key).
    // fetch = FetchType.LAZY means the ninjas are only fetched when needed.
    @OneToMany(mappedBy = "dojo", fetch = FetchType.LAZY)
    private List<Ninja> ninjas;

    // Empty constructor required by JPA
    public Dojo() {
    }

    // Runs right before the row is first saved: sets createdAt automatically
    @PrePersist
    protected void onCreate() {
        this.createdAt = new Date();
    }

    // Runs right before the row is updated: sets updatedAt automatically
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = new Date();
    }

    // ----- getters and setters -----
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public List<Ninja> getNinjas() {
        return ninjas;
    }

    public void setNinjas(List<Ninja> ninjas) {
        this.ninjas = ninjas;
    }
}