# Generated by Django 6.0.5 on 2026-06-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_ninja_dojo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
