# Generated by Django 5.2.7 on 2025-11-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_gamemanager_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameManager',
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
