# Generated by Django 5.2.7 on 2025-11-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_delete_gamemanager_alter_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
