# Generated by Django 5.2.7 on 2025-11-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_remove_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='relese_date',
            field=models.DateField(null=True, default='2024-04-01'),
        ),
    ]
