# Generated by Django 6.0.5 on 2026-06-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_alter_game_relese_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2024-04-01'),
        ),
    ]
