# Generated by Django 6.0.5 on 2026-06-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0008_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
