# Generated by Django 6.0.5 on 2026-06-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0009_remove_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='relese_date',
            field=models.DateField(),
        ),
    ]
