# Generated by Django 6.0.6 on 2026-06-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_game_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='users',
        ),
    ]
